package:
  name: mcm
  version: v1.0a4

source:
  git_rev: 
  git_url: https://github.com/VolkerSiep/MariasCardMaker.git

build:
  noarch: python
  number: 0
  script: "python setup.py install"

requirements:
  build:
    - python >=3
    - wxpython >=4.0
    - openpyxl >=2.0
    - setuptools

  run:
    - python >=3
    - wxpython >=4.0
    - openpyxl >=2.0

about:
  license: GPL-3.0 
  license_file: LICENSE.txt

