package:
  name: mcm
  version: "V1.0a1"

source:
  git_rev: V1.0a1
  git_url: https://github.com/VolkerSiep/MariasCardMaker.git

build:
  noarch: python
  number: 0
  script: "python setup.py install"

requirements:
  run:
    - python >=3.7
    - wxpython >=4.0
    - openpyxl >=3.0
    - numpy >=1.17

about:
  license: GPL-3.0 
  license_file: LICENSE.txt

