package:
  name: mcm
  version: "v1.0a2"

source:
  git_rev: v1.0a2
  git_url: https://github.com/VolkerSiep/MariasCardMaker.git

build:
  noarch: python
  number: 0
  script: "python setup.py install"

requirements:
  build:
    - python >=3.7
    - numpy >=1.17

  run:
    - python >=3.7
    - wxpython >=4.0
    - openpyxl >=3.0
    - numpy >=1.17

about:
  license: GPL-3.0 
  license_file: LICENSE.txt

